-- 코드를 입력하세요
-- [1]
SELECT COUNT(DISTINCT(NAME)) as "count" FROM ANIMAL_INS WHERE NAME != "NULL";

-- [2]
SELECT COUNT(NAME)
FROM
(
    SELECT NAME
    FROM ANIMAL_INS
    WHERE NAME IS NOT NULL
    GROUP BY NAME
)
ANIMAL_INS;
