-- 코드를 입력하세요
-- SELECT HOUR(DATETIME) as "HOUR", COUNT(*) as "COUNT" FROM ANIMAL_OUTS WHERE HOUR(DATETIME) >= 0 AND HOUR(DATETIME) <= 23 GROUP BY HOUR(DATETIME) ORDER BY HOUR(DATETIME);

SET @hour = -1;
SELECT (@hour := @hour + 1) as "HOUR",
(
    SELECT COUNT(DATETIME) as "COUNT"
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) = @hour
) COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23;
